import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import com.fasterxml.jackson.databind.node.ArrayNode
import com.fasterxml.jackson.databind.node.ObjectNode
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory

plugins {
    kotlin("jvm") version "2.4.20"
    kotlin("plugin.serialization") version "2.4.20"
    `java-library`
    `maven-publish`
    signing
    id("org.jetbrains.dokka") version "2.2.0"
    id("org.openapi.generator") version "7.25.0"
}

group = "com.classicchess"
version = "0.1.0"
repositories { mavenCentral() }

// Built with the current Kotlin compiler but published for Kotlin 2.1: the
// client's stdlib and metadata stay readable by older consumers, including
// the Android app's AGP-bundled compiler (android/andromeda-native).
kotlin {
    coreLibrariesVersion = "2.1.20"
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8)
        apiVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_1)
        languageVersion.set(org.jetbrains.kotlin.gradle.dsl.KotlinVersion.KOTLIN_2_1)
    }
}
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    withSourcesJar()
}
dependencies {
    implementation("com.squareup.okhttp3:okhttp:5.5.0")
    api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")
    api("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.11.0")
    testImplementation(kotlin("test-junit"))
    testImplementation("com.squareup.okhttp3:mockwebserver:5.5.0")
}
dependencyLocking { lockAllConfigurations() }

// Response models are generated by openapi-generator from the OpenAPI contract
// and committed under src/generated/kotlin, so an API change never silently
// changes the Android app's models: `generateModels` rewrites them and
// `checkContract` fails when they drift from the contract.
val openApiSpec = file("contracts/openapi.yaml").takeIf { it.isFile }
    ?: file("../../core/templates/core/pages/openapi.yaml")
val generatedModelRoot = "src/generated/kotlin"
val generatedModelPackageDir = "com/classicchess/api"
val openApiOutput = layout.buildDirectory.dir("openapi")
val generatorSpec = layout.buildDirectory.file("openapi-input/openapi.json")
sourceSets.main { kotlin.srcDir(generatedModelRoot) }

// openapi-generator 7.25's OpenAPI 3.1 support is beta: an allOf model loses
// the nullability of its members' 3.1 `type: [T, "null"]` and `anyOf` null
// fields, and `const` fields become untyped. The generator therefore reads the
// same contract written in 3.0 terms (`nullable`, plain types).
fun downlevelSchemaKeywords(node: JsonNode, parentKey: String? = null) {
    // Example and literal values are data, not schemas.
    if (parentKey in setOf("example", "examples", "default", "enum", "const")) return
    // Keys of these maps are names (a property may be called `default`).
    val names = parentKey in setOf("properties", "schemas", "paths", "responses", "content", "headers")
    node.fields().forEach { (key, child) -> downlevelSchemaKeywords(child, if (names) null else key) }
    if (node is ArrayNode) node.forEach { downlevelSchemaKeywords(it, parentKey) }
    if (node !is ObjectNode || names) return
    (node.get("type") as? ArrayNode)?.let { types ->
        val kinds = types.map { it.asText() }
        val concrete = kinds - "null"
        if ("null" in kinds) node.put("nullable", true)
        if (concrete.size == 1) node.put("type", concrete.single()) else node.remove("type")
    }
    for (keyword in listOf("anyOf", "oneOf")) {
        val members = node.get(keyword) as? ArrayNode ?: continue
        val concrete = members.filterNot { it.size() == 1 && it.path("type").asText() == "null" }
        if (concrete.size == members.size()) continue
        node.put("nullable", true)
        node.remove(keyword)
        val only = concrete.singleOrNull()
        when {
            only == null -> node.putArray(keyword).addAll(concrete)
            only.has("\$ref") -> node.putArray("allOf").add(only)
            else -> only.fields().forEach { (key, value) -> if (!node.has(key)) node.set<JsonNode>(key, value) }
        }
    }
    (node.get("enum") as? ArrayNode)?.let { values ->
        val concrete = values.filterNot { it.isNull }
        if (concrete.size != values.size()) {
            node.put("nullable", true)
            node.putArray("enum").addAll(concrete)
        }
    }
    node.remove("const")?.let { value ->
        if (!node.has("type")) {
            node.put("type", when {
                value.isTextual -> "string"
                value.isBoolean -> "boolean"
                value.isIntegralNumber -> "integer"
                value.isNumber -> "number"
                else -> "object"
            })
        }
    }
}
val downlevelOpenApi = tasks.register("downlevelOpenApi") {
    inputs.file(openApiSpec)
    outputs.file(generatorSpec)
    doLast {
        val contract = ObjectMapper(YAMLFactory()).readTree(openApiSpec) as ObjectNode
        contract.put("openapi", "3.0.3")
        downlevelSchemaKeywords(contract)
        generatorSpec.get().asFile.apply { parentFile.mkdirs() }
            .writeText(ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(contract))
    }
}

tasks.openApiGenerate { dependsOn(downlevelOpenApi) }
openApiGenerate {
    generatorName.set("kotlin")
    inputSpec.set(generatorSpec.get().asFile.absolutePath)
    outputDir.set(openApiOutput.get().asFile.absolutePath)
    cleanupOutput.set(true)
    packageName.set("com.classicchess.api")
    modelPackage.set("com.classicchess.api")
    // Component and inline response models only; operations are hand-written.
    globalProperties.set(mapOf("models" to "", "modelDocs" to "false", "modelTests" to "false"))
    // Skips request/response bodies declared inline on operations, and the
    // Lichess explorer passthrough that is served as a JsonObject below.
    ignoreFileOverride.set(file("openapi-generator-ignore").absolutePath)
    configOptions.set(mapOf(
        "serializationLibrary" to "kotlinx_serialization",
        "sourceFolder" to "src/main/kotlin",
        "dateLibrary" to "string",
        "enumPropertyNaming" to "UPPERCASE",
    ))
    // A value added to an API enum decodes as UNKNOWN_DEFAULT_OPEN_API
    // instead of failing every older client.
    additionalProperties.set(mapOf("enumUnknownDefaultCase" to "true"))
    // Wire types every kotlinx.serialization consumer can decode without a
    // contextual serializer; untyped `{}` schemas and the `type: null` items
    // of always-empty arrays become JSON.
    typeMappings.set(mapOf(
        "integer" to "kotlin.Long",
        "number" to "kotlin.Double",
        "URI" to "kotlin.String",
        "UUID" to "kotlin.String",
        "AnyType" to "JsonElement",
        "null" to "JsonElement",
    ))
    importMappings.set(mapOf(
        "JsonElement" to "kotlinx.serialization.json.JsonElement",
        "JsonObject" to "kotlinx.serialization.json.JsonObject",
    ))
    // The Kotlin generator folds an anyOf of several shapes into one class
    // whose fields are all required, so those unions stay JSON for callers to
    // inspect. It also cannot emit the Lichess explorer passthrough's
    // object-with-extra-properties members.
    schemaMappings.set(mapOf(
        "LichessOpeningExplorer" to "JsonObject",
        "PublicEventAbout_crosstable" to "JsonElement",
        "SiteSearchPage_results" to "JsonElement",
    ))
    nameMappings.set(mapOf("entries" to "entries"))
    inlineSchemaOptions.set(mapOf("ARRAY_ITEM_SUFFIX" to "Item", "SKIP_SCHEMA_REUSE" to "true"))
    inlineSchemaNameMappings.set(mapOf(
        "AnnotatedGame_allOf_annotation" to "AnnotatedGameAnnotation",
        "AnnotatedGame_allOf_annotation_notes" to "AnnotatedGameAnnotationNotesItem",
        "AnnotatedGame_allOf_book" to "AnnotatedGameBook",
        "PublicPlayer_allOf_archive_bucket" to "PublicPlayerArchiveBucket",
        "PublicPlayer_allOf_portrait" to "PublicPlayerPortrait",
    ))
}
val generatedModelSource = openApiOutput.map { it.dir("src/main/kotlin/$generatedModelPackageDir") }
// The generator's templates leave trailing spaces and blank last lines, which
// the repository whitespace gate rejects in committed sources.
fun tidyGeneratedSource(text: String) = text.lines().joinToString("\n") { it.trimEnd() }.trimEnd() + "\n"
val generateModels = tasks.register<Sync>("generateModels") {
    dependsOn(tasks.openApiGenerate)
    from(generatedModelSource)
    into("$generatedModelRoot/$generatedModelPackageDir")
    doLast {
        destinationDir.walkTopDown().filter { it.isFile }.forEach { it.writeText(tidyGeneratedSource(it.readText())) }
    }
}
// Builds read the committed models; `generateModels test` refreshes them first.
tasks.compileKotlin { mustRunAfter(generateModels) }
tasks.named("sourcesJar") { mustRunAfter(generateModels) }
val checkContract = tasks.register("checkContract") {
    dependsOn(tasks.openApiGenerate)
    val expectedDir = generatedModelSource.map { it.asFile }
    val committedDir = file("$generatedModelRoot/$generatedModelPackageDir")
    doLast {
        fun contents(dir: File, read: (File) -> String) = dir.walkTopDown().filter { it.isFile }
            .associate { it.relativeTo(dir).invariantSeparatorsPath to read(it) }
        val expected = contents(expectedDir.get()) { tidyGeneratedSource(it.readText()) }
        val committed = if (committedDir.isDirectory) contents(committedDir) { it.readText() } else emptyMap()
        val drift = (expected.keys + committed.keys).filter { expected[it] != committed[it] }.sorted()
        if (drift.isNotEmpty()) {
            throw GradleException(
                "Kotlin models differ from OpenAPI (${drift.joinToString()}); run ./gradlew generateModels.",
            )
        }
    }
}
tasks.named("check") { dependsOn(checkContract) }
tasks.test {
    maxParallelForks = 1
    val fixtures = file("contracts/client-fixtures.json").takeIf { it.isFile }
        ?: file("../../docs/api/client-fixtures.json")
    inputs.file(fixtures)
    systemProperty("classicchess.fixtures", fixtures.absolutePath)
}

val documentationJar by tasks.registering(Jar::class) {
    archiveClassifier.set("javadoc")
    from(tasks.dokkaGeneratePublicationHtml.flatMap { it.outputDirectory })
}
val releaseMetadata = file("contracts/sdk-release.json").takeIf { it.isFile }
    ?: file("../../docs/api/sdk-release.json")
val sdkRelease = groovy.json.JsonSlurper().parse(releaseMetadata) as Map<*, *>

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            artifact(documentationJar)
            pom {
                name.set("Classic Chess Kotlin API client")
                description.set("Typed public archive client for Kotlin JVM and Android")
                url.set("https://classicchess.com/api/")
                developers {
                    developer {
                        id.set("Andromeda1957")
                        name.set("Christian Walls")
                        url.set("https://classicchess.com/")
                    }
                }
                scm {
                    url.set("https://github.com/Andromeda1957/classicchess-api-kotlin")
                    connection.set("scm:git:https://github.com/Andromeda1957/classicchess-api-kotlin.git")
                    developerConnection.set("scm:git:ssh://git@github.com/Andromeda1957/classicchess-api-kotlin.git")
                }
                if (sdkRelease["license"] != null) {
                    licenses {
                        license {
                            name.set(sdkRelease["license"].toString())
                            url.set(sdkRelease["license_url"].toString())
                            distribution.set("repo")
                        }
                    }
                }
            }
        }
    }
    repositories {
        maven { name = "LocalPackage"; url = uri(layout.buildDirectory.dir("repository")) }
    }
}
signing {
    val key = providers.environmentVariable("SDK_SIGNING_KEY").orNull
    val password = providers.environmentVariable("SDK_SIGNING_PASSWORD").orNull
    if (key != null) {
        useInMemoryPgpKeys(key, password)
        sign(publishing.publications["maven"])
    }
}
tasks.register<Zip>("packageClient") {
    dependsOn("check", "publishMavenPublicationToLocalPackageRepository")
    archiveFileName.set("classicchess-kotlin-api-${project.version}.zip")
    destinationDirectory.set(layout.projectDirectory.dir("artifacts"))
    from(layout.buildDirectory.dir("repository")) { into("repository") }
    from("README.md")
    from("LICENSE")
}
tasks.register<JavaExec>("verifyPreview") {
    dependsOn("testClasses")
    classpath = sourceSets["test"].runtimeClasspath
    mainClass.set("com.classicchess.api.PreviewCheckKt")
    args(providers.gradleProperty("apiBaseUrl").getOrElse("http://127.0.0.1:8000"))
}
